apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{PROJECT}}-{{BRANCH}}
  namespace: {{NAMESPACE}} 
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-origins: "http://{{URL}}"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - {{URL}}
    secretName: {{PROJECT}}-{{BRANCH}}
  rules:
  - host: {{URL}}
    http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: {{NAME}}
            port:
              number: {{PORT}}